name: Run e2e CI for staging env

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download and install chrome
        run: |
          apt-get update
          apt-get -y install sudo
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_95.0.4638.69-1_amd64.deb
          sudo apt -y install ./google-chrome-stable_95.0.4638.69-1_amd64.deb
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: npm run install
        run: yarn install
      - name: Start server
        run: npm run start
      - name: Run test
        run: npm run test
